parameters:
    rate_limit:

services:
    rate_limit.listener.rate_limit:
        class: Goksagun\RateLimitBundle\EventListener\RateLimitListener
        arguments: ['%rate_limit%', '@snc_redis.default_client']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 7 }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
